//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Beamable.Server.Clients
{
    using System;
    using Beamable.Platform.SDK;
    using Beamable.Server;
    
    
    /// <summary> A generated client for <see cref="Beamable.Microservices.ThetaFederation.ThetaFederation"/> </summary
    public sealed class ThetaFederationClient : MicroserviceClient, Beamable.Common.IHaveServiceName, Beamable.Common.ISupportsFederatedLogin<Beamable.Theta.Common.ThetaCloudIdentity>, Beamable.Common.ISupportsFederatedInventory<Beamable.Theta.Common.ThetaCloudIdentity>
    {
        
        public ThetaFederationClient(BeamContext context = null) : 
                base(context)
        {
        }
        
        public string ServiceName
        {
            get
            {
                return "ThetaFederation";
            }
        }
        
        /// <summary>
        /// Call the InitializeContract method on the ThetaFederation microservice
        /// <see cref="Beamable.Microservices.ThetaFederation.ThetaFederation.InitializeContract"/>
        /// </summary>
        public Beamable.Common.Promise<string> InitializeContract()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("ThetaFederation", "InitializeContract", serializedFields);
        }
        
        /// <summary>
        /// Call the GetRealmAccount method on the ThetaFederation microservice
        /// <see cref="Beamable.Microservices.ThetaFederation.ThetaFederation.GetRealmAccount"/>
        /// </summary>
        public Beamable.Common.Promise<string> GetRealmAccount()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("ThetaFederation", "GetRealmAccount", serializedFields);
        }
        
        /// <summary>
        /// Call the GetDefaultContract method on the ThetaFederation microservice
        /// <see cref="Beamable.Microservices.ThetaFederation.ThetaFederation.GetDefaultContract"/>
        /// </summary>
        public Beamable.Common.Promise<string> GetDefaultContract()
        {
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            return this.Request<string>("ThetaFederation", "GetDefaultContract", serializedFields);
        }
        
        /// <summary>
        /// Call the ProcessTransaction method on the ThetaFederation microservice
        /// <see cref="Beamable.Microservices.ThetaFederation.ThetaFederation.ProcessTransaction"/>
        /// </summary>
        public Beamable.Common.Promise<Beamable.Common.Unit> ProcessTransaction(string transactionHash)
        {
            object raw_transactionHash = transactionHash;
            System.Collections.Generic.Dictionary<string, object> serializedFields = new System.Collections.Generic.Dictionary<string, object>();
            serializedFields.Add("transactionHash", raw_transactionHash);
            return this.Request<Beamable.Common.Unit>("ThetaFederation", "ProcessTransaction", serializedFields);
        }
    }
    
    internal sealed class MicroserviceParametersThetaFederationClient
    {
        
        [System.SerializableAttribute()]
        internal sealed class ParameterSystem_String : MicroserviceClientDataWrapper<string>
        {
        }
    }
    
    [BeamContextSystemAttribute()]
    public static class ExtensionsForThetaFederationClient
    {
        
        [Beamable.Common.Dependencies.RegisterBeamableDependenciesAttribute()]
        public static void RegisterService(Beamable.Common.Dependencies.IDependencyBuilder builder)
        {
            builder.AddScoped<ThetaFederationClient>();
        }
        
        public static ThetaFederationClient ThetaFederation(this Beamable.Server.MicroserviceClients clients)
        {
            return clients.GetClient<ThetaFederationClient>();
        }
    }
}
